---
- name: jdk 11
  hosts: appservers
  become: yes
  tasks:
    - name: install jdk11
      ansible.builtin.apt:
        update_cache: true
        name: "{{ java_package }}"
        state: present
    - name: create group
      ansible.builtin.group:
        name: "{{group_name}}"
        state: present
    - name: create user
      ansible.builtin.user:
        name: "{{ user_name }}"
        group: "{{ group_name }}"
        create_home: yes
        home: "{{ User_home }}"
        shell: "{{user_shell}}"
        state: present
    - name: get tomcat stats
      ansible.builtin.stat:
        path: "{{ User_home }}/latest/bin/startup.sh"
      register: tomcat_startup
    - name: untar the file
      ansible.builtin.unarchive:
        src: "https://www-eu.apache.org/dist/tomcat/tomcat-{{ major_version }}/v{{ version }}/bin/apache-tomcat-{{ version }}.tar.gz"
        dest: "{{ User_home }}"
        remote_src: yes
      when: not tomcat_startup.stat.exists
    - name: link the file
      ansible.builtin.file:
        src: "{{ User_home }}/apache-tomcat-{{ version }}"
        dest: "{{ User_home }}/latest"
        state: link
    - name: permissions
      ansible.builtin.file:
        dest: "{{ User_home }}"
        recurse: yes
        owner: "{{user_name}}"
        group: "{{group_name}}"
        state: directory
    - name: running shell
      ansible.builtin.command: "sudo sh -c 'chmod +x {{ User_home }}/latest/bin/*.sh'"
      when: not tomcat_startup.stat.exists
    - name: copy tomcat service
      ansible.builtin.copy:
        src: tomcat.service
        dest: "/etc/systemd/system/{{ tomcat_service }}"
        group: "{{group_name}}"
        owner: "{{user_name}}"
      when: ansible_facts['distribution'] == "Ubuntu"
    - name: copy tomcat service
      ansible.builtin.copy:
        src: centos_tomcat.service
        dest: "/etc/systemd/system/{{ tomcat_service }}"
        group: "{{group_name}}"
        owner: "{{user_name}}"
      when: ansible_facts['distribution'] == "CentOS"
    - name: demon reload
      ansible.builtin.systemd:
        name: "{{ tomcat_service }}"
        daemon_reload: yes
        enabled: true
        state: "started"
    - name: copy context xml
      ansible.builtin.copy:
        src: context.xml
        dest: "{{ User_home }}/latest/webapps/manager/META-INF/context.xml"
        group: "{{group_name}}"
        owner: "{{user_name}}"
    - name: copy host context xml
      ansible.builtin.copy:
        src: host-context.xml
        dest: "{{ User_home }}/latest/webapps/host-manager/META-INF/context.xml"
        group: "{{group_name}}"
        owner: "{{user_name}}"
    - name: copy user xml
      ansible.builtin.copy:
        src: tomcat-users.xml
        dest: "{{ User_home }}/latest/conf/tomcat-users.xml"
        group: "{{group_name}}"
        owner: "{{user_name}}"
    - name: reload daemon and start tomcat
      ansible.builtin.systemd:
        name: "{{ tomcat_service }}"
        daemon_reload: yes
        enabled: yes
        state: started
