---
- name: jdk 11
  hosts: all
  become: yes
  vars:
    java_package: openjdk-11-jdk
    version: "10.1.8"
    user_name: tomcat
    group_name: tomcat
    home: "/opt/tomcat/"
  tasks:
    - name: install jdk11
      ansible.builtin.apt:
        update_cache: true
        name: "{{ java_package}}"
        state: present
    - name: create group
      ansible.builtin.group:
        name: tomcat
        state: present
    - name: create user
      ansible.builtin.user:
        create_home: yes
        name: tomcat
        group: tomcat
        home: "{{ home }}"
        shell: /bin/false
        state: present
    - name: untar the file
      ansible.builtin.unarchive:
        src: "https://www-eu.apache.org/dist/tomcat/tomcat-10/v{{ version }}/bin/apache-tomcat-{{ version }}.tar.gz"
        dest: "{{ home }}"
        remote_src: yes
    - name: link the file
      ansible.builtin.file:
        src: "{{ home }}/apache-tomcat-{{ version }}"
        dest: "{{ home }}/latest"
        state: link
    - name: permissions
      ansible.builtin.file:
        dest: "{{ home }}/latest"
        recurse: yes
        owner: "{{user_name}}"
        group: "{{group_name}}"
        state: directory
    - name: running shell
      ansible.builtin.command: sudo sh -c 'chmod +x {{ home }}/latest/bin/*.sh'
    - name: copy tomcat service
      ansible.builtin.copy:
        src: tomcat.service
        dest: /etc/systemd/system/tomcat.service
        group: "{{group_name}}"
        owner: "{{user_name}}"
    - name: demon reload
      ansible.builtin.systemd:
        name: tomcat.service
        daemon_reload: yes
        enabled: true
        state: "started"
    - name: copy context xml
      ansible.builtin.copy:
        src: context.xml
        dest: "{{ home }}/latest/webapps/manager/META-INF/context.xml"
        group: "{{group_name}}"
        owner: "{{user_name}}"
    - name: copy host context xml
      ansible.builtin.copy:
        src: host-context.xml
        dest: "{{ home }}/latest/webapps/host-manager/META-INF/context.xml"
        group: "{{group_name}}"
        owner: "{{user_name}}"
    - name: copy user xml
      ansible.builtin.copy:
        src: tomcat-users.xml
        dest: "{{ home }}/latest/conf/tomcat-users.xml"
        group: "{{group_name}}"
        owner: "{{user_name}}"
    - name: demon reload
      ansible.builtin.systemd:
        name: tomcat.service
        state: "restarted"
